### ISSUE TITLE
Категории - серверная часть

### ISSUE THREAD

**Issue by serij123** [DenysLytvynenko/eshop#1]
Необходимо сделать REST-сервис для категорий нашего магазина. 
каждый элемент категории это:
id - набор символов (напр, electronic, pc_peripherals, etc)
locale - объект , например:
{"en_US":"PC Peripherals",
"ru_RU":"Периферийные устройства"
}
parent_id - ид парента
path - массив до родителя. например
["goods","pc_components","pc_peripherals"]
необходмо написать модель, сервис, репозиторий(интерфейсы, спринг сам сделает нам реализацию)  и REST-контроллер, в котором будут методы:

**Comment by serij123** [comment]
Все наши REST контроллеры должны быть доступны по общему URLу вида:
http://host:port/eshop/rest/v1/
eshop - общий маппинг приклада
rest - общий путь до всех REST-контроллеров
v1 - идентификатор версии REST

контроллер c категориями маппится на http://host:port/eshop/rest/v1/categories
Методы , которые должны быть в контроллере (маппятся на корень, т.е. на categories), но только на разные http-методы:
PUT - принимает json с категорией, сохраняет в бд
POST - обновляет json с категорией,
GET - получение всех категорий (списком)/, пока без параметров.
/{id} - получение информации о категории по ее идентификатору (см @PathVariable)

@RestController - это аннотация для рест-контроллера.
пример маппинга:

    @RequestMapping(value = "",
            method = RequestMethod.GET)
    public GetCategoriesResponse getAll() { ..}

    @RequestMapping(value = "",
            method = RequestMethod.POST)
    public WebResult addCategory(@RequestBody Category req) {..}
WebResult - возвращает результат работы , состоит из полей:
    private Integer code;
    private String description;
code - 0  - успех, 1 - какая-то ошибка, 2-  другая ошибка...
GetCategoriesResponse - это который содержит WebResult, но еще в  добавок содержит List<Categories>

**Comment by serij123** [comment]
addCategory, updateCategory - должны возвращать CategoryWebResult, который содержит WebResult и идентификатор созданной или обновленной сущности

**Comment by DenysLytvynenko** [comment]
Done.
